15-matrices.yaml

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -25,12 +25,12 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
-      - name: Fail if experiment
-        if: matrix.tag == 'experimental'
-        run: exit 1
+      #- name: Fail if experiment
+       # if: matrix.tag == 'experimental'
+        #run: exit 1
       - name: Perform some tasks
         run: |
          echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
-         sleep 10
+         #sleep 10
       - name: Upload test results
         run: echo "Uploading test results"
